=== lindsayevans/bake/schema.json
{
  "$ref": "#/definitions/Config",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Config": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projectDependencies": {
          "additionalProperties": {
            "$ref": "#/definitions/ConfigProjectDependency"
          },
          "type": "object"
        },
        "targets": {
          "additionalProperties": {
            "$ref": "#/definitions/ConfigTarget"
          },
          "type": "object"
        },
        "variables": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "name",
        "version"
      ],
      "type": "object"
    },
    "ConfigProjectDependency": {
      "additionalProperties": false,
      "properties": {
        "install": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "source": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ConfigTarget": {
      "additionalProperties": false,
      "properties": {
        "cmd": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "default": {
          "type": "boolean"
        },
        "in": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "variables": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  }
}

=== lindsayevans/bake/examples/glob.jache.json
{
  "$schema": "../schema.json",
  "name": "My Awesome Tool",
  "version": "1.2.3-alpha",
  "description": "An awesome tool built in C",
  "variables": {
    "src": "./src",
    "out": "./out",
    "cc": "clang",
    "ccflags": "-Wall",
    "ldflags": ""
  },
  "targets": {
    "clean": {
      "cmd": "rm -rf ${out}/*"
    },
    "install": {
      "cmd": [
        "cp ${out}/**/*.o /usr/local/lib/",
        "cp ${src}/**/*.h /usr/local/include/",
        "cp ${out}/awesometool /usr/local/bin/"
      ]
    },
    "${out}/*.o": {
      "in": "${src}/*.c",
      "cmd": "${cc} -c ${ccflags} -o ${:target} ${:in}"
    },
    "${out}/awesometool": {
      "default": true,
      "in": ["${out}/*.o"],
      "cmd": "${cc} ${ldflags} -o ${:target} ${:in}"
    }
  }
}

=== lindsayevans/bake/examples/deps.json
{
  "$schema": "../schema.json",
  "name": "My Awesome Tool",
  "version": "1.2.3-alpha",
  "description": "An awesome tool with dependencies",
  "variables": {
    "lib": "./lib"
  },
  "projectDependencies": {
    "${lib}/uthash/uthash.h": {
      "source": "https://github.com/troydhanson/uthash/blob/master/src/uthash.h"
    },
    "${lib}/log.c/": {
      "source": "git://https://github.com/rxi/log.c",
      "install": "cp src/* ./ && rm -rf src"
    },
    "${lib}/something/": {
      "source": "../libsomething/"
    }
  },
  "targets": {
    "clean": {
      "cmd": "rm -rf ${lib}/*"
    }
  }
}

=== lindsayevans/bake/examples/basic.json
{
  "$schema": "../schema.json",
  "name": "My Awesome Tool",
  "version": "1.2.3-alpha",
  "description": "An awesome tool built in C",
  "variables": {
    "src": "./src",
    "out": "./out",
    "cc": "clang",
    "ccflags": "-Wall",
    "ldflags": "-llibcurl"
  },
  "targets": {
    "default": {},
    "clean": {
      "cmd": "rm -rf ${out}/*"
    },
    "install": {
      "cmd": [
        "cp ${out}/*.o /usr/local/lib/",
        "cp ${src}/*.h /usr/local/include/",
        "cp ${out}/awesometool /usr/local/bin/"
      ]
    },
    "${out}/main.o": {
      "in": "${src}/main.c",
      "cmd": "${cc} -c ${ccflags} -o ${:target} ${:in}"
    },
    "${out}/foo.o": {
      "in": "${src}/foo.c",
      "cmd": "${cc} -c ${ccflags} -o ${:target} ${:in}"
    },
    "${out}/awesometool": {
      "default": true,
      "in": ["${out}/main.o", "${out}/foo.o"],
      "cmd": "${cc} ${ldflags} -o ${:target} ${:in}"
    }
  }
}
